baseURL = 'https://hugo.kk-wuyue.top/'
locale = 'zh-cn'
title = '初夏札记'
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  defaultTheme = "auto"