baseURL = 'https://hugo.kk-wuyue.top/'
locale = 'zh-cn'
title = '初夏札记'
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    tabWidth = 4
  
[outputs]
  home = ["HTML","RSS","JSON"]
  
[[menu.main]]
dentifier = "archives"
name = "归档"
url = "/archives"
weight = 5

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 15